export namespace vis::ecs {
using vis::ecs::allocate_unique;
using vis::ecs::allocation_deleter;
using vis::ecs::make_obj_using_allocator;
using vis::ecs::propagate_on_container_copy_assignment;
using vis::ecs::propagate_on_container_move_assignment;
using vis::ecs::propagate_on_container_swap;
using vis::ecs::to_address;
using vis::ecs::uninitialized_construct_using_allocator;
using vis::ecs::uses_allocator_construction_args;
} // namespace vis::ecs